### ISSUE TITLE
How to get SCAPE.obj？

### ISSUE THREAD

**Issue by lhjjy** [mad-lab-fau/BASH-Model#10]
Hello,
I've successfully run your project. I am trying to use your package with some of my data. 
This baseline model is generic, and I don't know if it's necessary to modify it, but I'd like to know how SCAPE.obj got it. I know that the underlying articulated skeleton and the attached marker points are modeled in Blender, but I want to know how the surface mesh inside this is obtained.
Thanks in advance for your help!

**Comment by MarliesNit** [comment]
Hi, 
please see the following publication for details of the SCAPE implementation:
Anguelov, D., Srinivasan, P., Koller, D., Thrun, S., Rodgers,J., and Davis, J. (2005). SCAPE: Shape Completionand Animation of People. In ACM Transactions onGraphics, volume 24, pages 408–416.
