### ISSUE TITLE
Need help for the installation........

### ISSUE THREAD

**Issue by hwy1992129** [mad-lab-fau/BASH-Model#5]
Hello,
For the dependencies, SuitSparse package: suitsparse + amd + umfpack (>= 5.1.2).
The official SuitSparse doesn't support Windows well.
Are you using the [unoffical SuitSparse for windows version](https://github.com/jlblancoc/suitesparse-metis-for-windows)?
There is a "libmwlapack.lib" I failed to get it... Does it come from the matlab version of lapack?
I am using the SDK from OpenSim 4.3 binary version.
There is an error in the [code in osim.cpp](https://github.com/mad-lab-fau/BASH-Model/blob/main/src/osim.cpp#L94)....
`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2440	'initializing': cannot convert from 'OpenSim::DataAdapter::OutputTables' to 'OpenSim::TimeSeriesTable_<SimTK::Real>'	SCAPE	E:\innovision2021\BASH-Model-main\BASH-Model-main\src\osim.cpp	94	
`

**Comment by hwy1992129** [comment]
I think I probably figure it out........
Just want to make sure one thing...
Is removing "libmwlapack.lib" fine???

**Comment by MarliesNit** [comment]
The error might occur from changes in OpenSim. We used the code successfully with OpenSim 4.0.
