### ISSUE TITLE
Can't load sto from 2020_Nitschke_RunMaD.zip.... and some questions on the result..

### ISSUE THREAD

**Issue by hwy1992129** [mad-lab-fau/BASH-Model#6]
Hi,
Finally, I let BASH-Model run in my pc.
Since it has an [error ](https://github.com/mad-lab-fau/BASH-Model/blob/main/src/osim.cpp#L94), as mentioned in my previous [issue](https://github.com/mad-lab-fau/BASH-Model/issues/5), I modify that line into `OpenSim::TimeSeriesTable stoTable = OpenSim::TimeSeriesTable(filepath);`
I downloaded 2020_Nitschke_RunMaD.zip to test the program.
I can't load any sto to run it... I only can run the osim with mot file....

Besides, without the sto, I got the result below.
![image](https://user-images.githubusercontent.com/70329303/147777539-8be9bbcd-fe7a-497a-8133-26a512ab4dd7.png)
There are some cyan color lines near the arms. Do they represent the arms from the OpenSim skeleton (runMaD.osim)?
Does it mean the skeleton can't be under the SCAPE surface model?
![image](https://user-images.githubusercontent.com/70329303/147777760-642b4fa1-088b-4b1d-bb16-74271bbe066b.png)

**Comment by MarliesNit** [comment]
Nice, that some part is working already. 

As mentioned in the other issue, the error might be related to the OpenSim Version. This is probably also the reason why you cannot yet load the sto files. 

You are partly right. The cyan lines are not exactly the OpenSim skeleton, but they are the articulated skeleton. As discussed in our paper, the transformation with the pose-induced deformations enhances the realism of the visualized mesh, but also introduces inaccuracies in the visualization. When pressing M on your keyboard, you can switch off the mesh. By pressing 2 on the number pad, you get the animated motion before the applying the pose-induced deformations. When pressing 3 on the number pad, it will show again the animation after applying the pose-induced deformations. You can find more shortcuts in settings.h.

The other prominent cyan line simply connects the pelvis with the origin of the coordinate system.

**Comment by hwy1992129** [comment]
@Marlies93 Thanks for your answer. Can the osim skeleton be visualized with the SCAPE? In setting.h I see "bool showModelOsim = true;". Also, I see the LShift shortcut in the setting.h, but clicking it got nothing... And there are two shortcuts related to LShift.......

**Comment by hwy1992129** [comment]
@Marlies93 I changed the shortcut. The KEY_MODEL_OSIM toggle the cyan lines, red dots, and red lines - articulated skeleton, markers, muscles.
