### ISSUE TITLE
Issues on the versions of reading sto and the sto files in 2020_Nitschke_RunMaD.zip

### ISSUE THREAD

**Issue by hwy1992129** [mad-lab-fau/BASH-Model#7]
I finally let the program work with Muscle Activation.
It has an [error ](https://github.com/mad-lab-fau/BASH-Model/blob/main/src/osim.cpp#L94)if you are not using OpenSim 4.0 API. 
Change the code to `OpenSim::TimeSeriesTable stoTable = OpenSim::TimeSeriesTable(filepath);` may fix the error in OpenSim 4.1+ API.
The *.sto files from 2020_Nitschke_RunMaD.zip don't work in the program. The reason behind it may be the problem of format.....???
I open the *.sto using excel. The *.sto file from 2020_Nitschke_RunMaD.zip look like the following figure.
![image](https://user-images.githubusercontent.com/70329303/147984957-1f908ded-bb62-4a17-b57a-93fadfb3865f.png)
I modified the *.sto file and the program works well with Muscle Activation...
![image](https://user-images.githubusercontent.com/70329303/147985069-5c390425-556f-40a7-8550-c2a55ee42285.png)
![image](https://user-images.githubusercontent.com/70329303/147985280-7c936027-c80a-4d26-9657-782554430bbd.png)

**Comment by MarliesNit** [comment]
Happy to hear that your visualization of the muscle activations is working now! The sto files and all other OpenSim files of 2020_Nitschke_RunMaD.zip were created with OpenSim 4.0 as described in my paper (https://www.nature.com/articles/s41598-020-73856-w).  Hence, it might be that the sto file is not compatible to newer OpenSim versions. 

You can use the OpenSim GUI to update OpenSim files to newer formats. Tools -> Convert Files
